name: "payment-processing"

services:
  server:
    image: payment-processing-server
    container_name: payment-processing-server
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8091:8090"
    environment:
      SPRING_DATASOURCE_URL: ${PAYPROC_URL}
      SPRING_DATASOURCE_USERNAME: ${PAYPROC_USER}
      SPRING_DATASOURCE_PASSWORD: ${PAYPROC_PASSWORD}
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      db:
        condition: service_healthy
    mem_limit: 500mb
    cpus: 1

  db:
    image: postgres:17.9-bookworm
    container_name: payment-processing-db
    restart: always
    environment:
      POSTGRES_USER: ${PAYPROC_USER}
      POSTGRES_PASSWORD: ${PAYPROC_PASSWORD}
      POSTGRES_DB: ${PAYPROC_DB}
    volumes:
      - payment-processing-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${PAYPROC_DB} -U ${PAYPROC_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10
    mem_limit: 1g
    cpus: 1

  db-dev:
    extends:
      service: db
    container_name: payment-processing-db-dev
    ports:
      - "5443:5432"
    environment:
      POSTGRES_AUTH_METHOD: md5
    profiles: ["dev"]

volumes:
  payment-processing-pgdata:
