spring:
  application:
    name: PaymentProcessing
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    time-zone: UTC
  profiles:
    active: local

server:
  port: 8090
